version: "3.8"

services:
  cab-media-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Cassandra__Host=51.79.254.106
      - Cassandra__Port=9042
      - Cassandra__UserName=cassandra
      - Cassandra__Password=cassandra
      - Cassandra__Keyspace=mediadb
      - EventBus__Connection=51.79.254.106
      - EventBus__UserName=guest
      - EventBus__Password=guest
      - EventBus__SubscriptionClientName=CabMediaService
      - EventBus__RetryCount=5
      - EventBus__ExchangeName=cabservice_event_bus
      - EventBus__AzureServiceBusEnabled=false
      - GRPC_PORT=81
      - PORT=80
      - OrchestratorType=K8S
      - MediaDbConnectionString=Host=51.79.254.106;Database=MediaDb;Username=postgres;Password=mysecretpassword
      - MinIOSettings__EndPoint=51.79.254.106:9000
      - MinIOSettings__AccessKey=cabvn
      - MinIOSettings__SecretKey=cabvn@test
      - MinIOSettings__BucketName=cabvn
      - MinIOSettings__Location=us-east-1
      # cassandra:
      # environment:
      # - CASSANDRA_USER=cassandra
      # - CASSANDRA_PASSWORD=cassandra

      # cassandra-init-data:
      # environment:
      # - CASSANDRA_USER=cassandra
      # - CASSANDRA_PASSWORD=cassandra

volumes:
  mongodata: null
networks:
  internal:
    name: cabvn
