version: "3.8"

services:
    cab-media-service:
        image: registry.gitlab.com/cabvn/cab-services/cab-media-service:latest
        container_name: cab-media-service
        restart: unless-stopped
        networks:
            - internal
volumes:
    mongodata:
networks:
    internal:
        name: cabvn
