version: "3.8"

services:
    
    cab-post-service:
        image: registry.gitlab.com/cabvn/cab-services/cab-post-service:latest
        container_name: cab-post-service
        restart: unless-stopped
        networks:
            - internal

volumes:
    mongodata:
networks:
    internal:
        name: cabvn
