version: "3.8"

services:
    cab-payment-service:
        image: registry.gitlab.com/cabvn/cab-services/cab-payment-service:latest
        container_name: cab-payment-service
        restart: unless-stopped
        networks:
            - internal

volumes:
    mongodata:
networks:
    internal:
        name: cabvn
